### PR TITLE
read files strictly in "Obelisk.Migration".

### LINKED ISSUE #115: hydra build is currently failing
Is this expected? I am already looking into it, whether I can find an obvious reason. I can reproduce the issue locally (obviously - thank you nix) and get a `too many open files` error:

```
ob: ./migration/f595b01939b4c87b7c146ea9ff331b39-4da182e21be35feeee484dc85be7a075/obelisk-upgrade: openFile: resource exhausted (Too many open files)
```

### PR DESCRIPTION
**Pull request by eskimor**
To avoid "too many open files" error.

This fixes #115 partly, I still get an error that is similar to the one on hydra:

```
No vertex found for HEAD (b0b562b83e8a198bb858deeb19d5868c)
✖ Checking existence of HEAD vertex
```

### CODE REVIEW

**Comment by srid** [comment]
> I still get an error that is similar to the one on hydra
> No vertex found for HEAD (b0b562b83e8a198bb858deeb19d5868c)

Yea, see #116

**Comment by eskimor** [comment]
thanks!

File: lib/migration/src/Obelisk/Migration.hs [hunk 1]
```diff
@@ -240,3 +240,8 @@ writeEdge dir actionFiles v1 v2 = do
       forM_ actionFiles $ \fp -> liftIO $
         writeFile (edgeDir </> T.unpack fp) ""
       pure $ Just edgeDir
+
+readFileStrict :: FilePath -> IO String
+readFileStrict = makeStrict <=< readFile
```
Comment (3noch) [inline lib/migration/src/Obelisk/Migration.hs]: [Text.IO.readFile](https://hackage.haskell.org/package/text-1.2.3.0/docs/Data-Text-IO.html#v:readFile) is strict and seems more appropriate here?

**Comment by ryantrinkle** [comment]
Yes; we should always be using Text anyway

File: lib/migration/src/Obelisk/Migration.hs (hunk 1 above)
Comment (eskimor) [reply lib/migration/src/Obelisk/Migration.hs]: Yep. I already had it checked out. Will fix.

File: lib/migration/src/Obelisk/Migration.hs [hunk 2]
```diff
@@ -95,7 +95,7 @@ readGraph root name = doesDirectoryExist root >>= \case
       let f = root </> (T.unpack $ v1 <> "-" <> v2) </> T.unpack graph
       doesFileExist f >>= \case
         True -> do
-          c <- readFile f >>= pure . parseEdgeMeta
+          c <- readFileStrict f >>= pure . parseEdgeMeta
```
Comment (eskimor) [inline lib/migration/src/Obelisk/Migration.hs]: but if we use T.readFile - what to do with parseEdgeMeta - just drop it? At the moment it is just a T.pack anyway, but I assume this is intended to do more at some point? Should I preserve the `Action` class and change it to:

```haskell
class Action action where
  parseEdgeMeta :: Text -> action

instance Action Text where
  parseEdgeMeta = id
```

Comment (eskimor) [reply lib/migration/src/Obelisk/Migration.hs]: @srid ?

Comment (srid) [reply lib/migration/src/Obelisk/Migration.hs]: @eskimor Yes, preserve but change it to use `Text` and `id` like you've written above.

Comment (eskimor) [reply lib/migration/src/Obelisk/Migration.hs]: awesome!

**Comment by eskimor** [comment]
Requested improvements are incorporated now! :-)

**Comment by kmicklas** [comment]
Can we just use [`readFile` from `Data.Text.IO`](http://hackage.haskell.org/package/text-1.2.3.0/docs/Data-Text-IO.html#v:readFile)? It's explicitly strict and avoids manually `pack`ing.

**Comment by eskimor** [comment]
> Can we just use readFile from Data.Text.IO? It's explicitly strict and avoids manually packing.

Yeah, thanks for reviewing! The latest version of this PR already does this. Are you somehow reviewing an older version or is something messed up with my PR?

**Comment by kmicklas** [comment]
@eskimor Oops, I must have clicked on the first commit by mistake.
